-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              11.4.2-MariaDB-log - mariadb.org binary distribution
-- S.O. server:                  Win64
-- HeidiSQL Versione:            12.1.0.6537
-- --------------------------------------------------------
-- --
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dump della struttura di tabella corsophp.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `email` varchar(64) NOT NULL,
  `fiscalcode` char(16) NOT NULL,
  `age` smallint(3) unsigned NOT NULL,
  `avatar` varchar(64) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `roletype` enum('user','editor','admin') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `u_fiscalcode` (`fiscalcode`),
  KEY `i_email` (`email`),
  KEY `i_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=217 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- Dump dei dati della tabella corsophp.users: ~189 rows (circa)
INSERT INTO `users` (`id`, `username`, `email`, `fiscalcode`, `age`, `avatar`, `password`, `roletype`) VALUES
	(2, 'Leopoldo Morandi', 'leopoldo.morandi70@infinitevoid.jap', 'AKCLDHRQLXRCJGLG', 44, '2_17195841294036.jpg', '$2y$10$w/oJdmT.ZQZMw544cCSwQ.FxqPV/jp8AWgW4lBvB.vlPEXrSVAt/e', 'editor'),
	(4, 'Enrico Formaggio', 'enrico.formaggio12@hotmail.it', 'NQOGWZXFLHYSUGSL', 27, '4_17195843390512.jpg', '$2y$10$Mq7qV25XU5O3RxVwbY4EaO3.c5Y7AMhcLQ1pHbmls6UsNlhPqWScK', 'user'),
	(5, 'Irene Sprocati', 'irene.sprocati66@iisviolamarchesini.edu.it', 'LEFTVZVKRGDVMEVV', 41, '', '$2y$10$wL83VJNkRTlxz1U0PBf9j.uJpfQE5h4UCcvMOGbFeIJROd4Pqxzji', 'admin'),
	(6, 'Ermenegilda Morandi', 'ermenegilda.morandi72@malevolentshrine.com', 'QPZKRVHATGZNPNIC', 19, NULL, '', 'user'),
	(7, 'Irene Alfieri', 'irene.alfieri54@yahoo.com', 'EOSZCPEFXZZHAWLC', 45, NULL, '', 'user'),
	(8, 'Eleonora Sterza', 'eleonora.sterza23@hotmail.it', 'AAFUQYPVLXMJPJQU', 25, NULL, '', 'user'),
	(9, 'Marcello Cherubin', 'marcello.cherubin81@yahoo.com', 'VAMLQCSMGSNKRDFC', 36, NULL, '', 'user'),
	(10, 'John Targa', 'john.targa47@hotmail.it', 'GBXOZAAQEJTDHSDW', 50, NULL, '', 'user'),
	(11, 'Leopoldo Anescu', 'leopoldo.anescu40@outlook.com', 'ARYVEZCRYQJKFKAE', 19, NULL, '', 'user'),
	(12, 'Noelle Borbone', 'noelle.borbone34@iisviolamarchesini.edu.it', 'XJEVEYEQXNGTMPLT', 44, NULL, '', 'user'),
	(13, 'John Cherubin', 'john.cherubin78@google.com', 'NFHRQGQUWQRXYIIM', 22, NULL, '', 'user'),
	(14, 'Mario Alfieri', 'mario.alfieri64@outlook.com', 'LUAQQDPIAKXSLUBB', 21, NULL, '', 'user'),
	(15, 'Sam Melon', 'sam.melon24@hotmail.it', 'FEQNWKFQWKUMOJOS', 48, NULL, '', 'user'),
	(16, 'Angelica Alfieri', 'angelica.alfieri10@infinitevoid.jap', 'WSSPWXAGTZFYWUGK', 45, NULL, '', 'user'),
	(17, 'Elena Vegro', 'elena.vegro55@infinitevoid.jap', 'WOMGNALYVWEWIXRN', 46, NULL, '', 'user'),
	(18, 'Noelle Cucu', 'noelle.cucu40@iisviolamarchesini.edu.it', 'JCNMFBGDCYGIAJCJ', 29, NULL, '', 'user'),
	(20, 'Sam Sprocati', 'sam.sprocati43@iisviolamarchesini.edu.it', 'MZLDUAEVGPDRHXRR', 26, NULL, '', 'user'),
	(21, 'Fabio Sterza', 'fabio.sterza45@hotmail.it', 'XLONPIORTSHYFJKQ', 39, NULL, '', 'user'),
	(23, 'Leopoldo Cherubin', 'leopoldo.cherubin27@outlook.com', 'BSUSYJKULVQVLJTA', 45, NULL, '', 'user'),
	(24, 'Vittoria Morandi', 'vittoria.morandi41@google.com', 'JNJFBUEXMBHLUOUO', 32, NULL, '', 'user'),
	(26, 'Elena Borbone', 'elena.borbone48@hotmail.it', 'CKQFULKMUBJPEDVV', 28, NULL, '', 'user'),
	(27, 'Leopoldo Gasparini', 'leopoldo.gasparini36@infinitevoid.jap', 'EJPOGUBQRYWFZVTG', 22, NULL, '', 'user'),
	(28, 'Ermenegilda Vegro', 'ermenegilda.vegro68@iisviolamarchesini.edu.it', 'PDUWJHSUDGPRMHNA', 18, NULL, '', 'user'),
	(29, 'Ermenegilda Sterza', 'ermenegilda.sterza23@infinitevoid.jap', 'EEWSQUMGXPICVXXJ', 44, NULL, '', 'user'),
	(30, 'Enrico Borbone', 'enrico.borbone71@yahoo.com', 'UZIHDBVJVCULAMLD', 50, NULL, '', 'user'),
	(31, 'Eleonora Cucu', 'eleonora.cucu48@iisviolamarchesini.edu.it', 'OUQYUPQZSWYHKPVE', 47, NULL, '', 'user'),
	(32, 'Ermenegilda Zadra', 'ermenegilda.zadra10@infinitevoid.jap', 'KHATXFWGOUIQTVEI', 20, NULL, '', 'user'),
	(33, 'Mario Sprocati', 'mario.sprocati17@hotmail.it', 'ZLRUJJVRMCGHANVE', 31, NULL, '', 'user'),
	(34, 'Ermenegilda Rossi', 'ermenegilda.rossi88@malevolentshrine.com', 'PNEUZQBWROQFBLYN', 19, NULL, '', 'user'),
	(35, 'Enrico Sterza', 'enrico.sterza61@malevolentshrine.com', 'SUYOXTAHHTLRZSLA', 48, NULL, '', 'user'),
	(36, 'Noelle Melon', 'noelle.melon63@infinitevoid.jap', 'DGNSICLKISALJCYS', 33, NULL, '', 'user'),
	(37, 'Marcello Alfieri', 'marcello.alfieri80@malevolentshrine.com', 'MCEYXZSIASMEKIMO', 23, NULL, '', 'user'),
	(38, 'Elena Cucu', 'elena.cucu22@iisviolamarchesini.edu.it', 'YELCSEFQINQOBWBH', 44, NULL, '', 'user'),
	(39, 'Goku Gasparini', 'goku.gasparini82@iisviolamarchesini.edu.it', 'VTSNZDMLKZAFQSHD', 29, NULL, '', 'user'),
	(40, 'Enrico Morandi', 'enrico.morandi51@google.com', 'KNVGUYQOSYSDMFFT', 25, NULL, '', 'user'),
	(41, 'Eleonora Melon', 'eleonora.melon15@infinitevoid.jap', 'BCANMEMNPQRNOQCJ', 18, NULL, '', 'user'),
	(42, 'Ermenegilda Rossi', 'ermenegilda.rossi99@google.com', 'RVRGIZAZIDDOAHAU', 43, NULL, '', 'user'),
	(43, 'Marcello Melon', 'marcello.melon61@infinitevoid.jap', 'CYUQOREHEIMACQZF', 18, NULL, '', 'user'),
	(44, 'Fabio Sprocati', 'fabio.sprocati16@hotmail.it', 'WWWEHFCQHAVWBMDQ', 29, NULL, '', 'user'),
	(45, 'Enrico Cherubin', 'enrico.cherubin73@infinitevoid.jap', 'JGVOQPHBHEMTEVGH', 25, NULL, '', 'user'),
	(46, 'Enrico Anescu', 'enrico.anescu94@hotmail.it', 'ESMLVWFCEROGPUFZ', 26, NULL, '', 'user'),
	(47, 'Fabio Formaggio', 'fabio.formaggio57@outlook.com', 'HVIQOBCICMYTXRNO', 37, NULL, '', 'user'),
	(49, 'Ermenegilda Vegro', 'ermenegilda.vegro42@infinitevoid.jap', 'TGRMYIWABLTSXPPO', 34, NULL, '', 'user'),
	(50, 'Ermenegilda Sterza', 'ermenegilda.sterza92@google.com', 'TFAVBHBDKJKTWUDH', 32, NULL, '', 'user'),
	(51, 'Marcello Cherubin', 'marcello.cherubin19@infinitevoid.jap', 'HJNPNODYFBFANRWB', 38, NULL, '', 'user'),
	(52, 'Enrico Cherubin', 'enrico.cherubin71@google.com', 'GGIYXAUQKPHFYDZZ', 45, NULL, '', 'user'),
	(53, 'Leopoldo Melon', 'leopoldo.melon96@outlook.com', 'GVYFVFAYDGFSFQVD', 50, NULL, '', 'user'),
	(54, 'Noelle Cucu', 'noelle.cucu77@yahoo.com', 'PRTROFCRKIUXFPUJ', 34, NULL, '', 'user'),
	(55, 'Enrico Alfieri', 'enrico.alfieri46@yahoo.com', 'IKADFORALSVXIIRV', 46, NULL, '', 'user'),
	(56, 'Sam Cucu', 'sam.cucu43@yahoo.com', 'KSKTPANMAXDNWMWH', 34, NULL, '', 'user'),
	(57, 'Elena Sulek', 'elena.sulek82@yahoo.com', 'ZUPMTLFUUSYVUSWL', 37, NULL, '', 'user'),
	(58, 'Leopoldo Borbone', 'leopoldo.borbone11@outlook.com', 'FSDCEXOUFJCJFBQT', 17, NULL, '', 'user'),
	(59, 'Irene Rossi', 'irene.rossi55@hotmail.it', 'ANUTJGHESSUOCNZE', 44, NULL, '', 'user'),
	(60, 'Angelica Targa', 'angelica.targa65@yahoo.com', 'BOJEYMCMFZFXPRAU', 49, NULL, '', 'user'),
	(62, 'Carloamianto Melon', 'carloamianto.melon92@outlook.com', 'WGLUFRNTXUMVUHRH', 37, NULL, '', 'user'),
	(63, 'Enrico Alfieri', 'enrico.alfieri68@infinitevoid.jap', 'RYSYQGFCVLKFTHCK', 44, NULL, '', 'user'),
	(64, 'Angelica Alfieri', 'angelica.alfieri18@outlook.com', 'HRPLUYLIUNTWQGVP', 33, NULL, '', 'user'),
	(65, 'Angelica Sulek', 'angelica.sulek64@iisviolamarchesini.edu.it', 'FCONVBSESZYEVHUY', 24, NULL, '', 'user'),
	(66, 'John Cherubin', 'john.cherubin73@yahoo.com', 'LIFURCSORCATSAXP', 44, NULL, '', 'user'),
	(67, 'Mario Morandi', 'mario.morandi49@infinitevoid.jap', 'OYPCKOLERYDAMENF', 42, NULL, '', 'user'),
	(68, 'Sam Rossi', 'sam.rossi76@hotmail.it', 'PLUPPDECUWKKEHKR', 39, NULL, '', 'user'),
	(69, 'Sam Sulek', 'sam.sulek74@iisviolamarchesini.edu.it', 'CPLYWANIWXRUZPSB', 9, NULL, '', 'user'),
	(70, 'Irene Gasparini', 'irene.gasparini99@yahoo.com', 'JGQRRMDCKJIGEOMQ', 30, NULL, '', 'user'),
	(71, 'Nicole Cherubin', 'nicole.cherubin37@yahoo.com', 'CYPTLKBAPTNSFIGN', 42, NULL, '', 'user'),
	(72, 'Carloamianto Anescu', 'carloamianto.anescu26@outlook.com', 'PHAQLJFJLDAGWNPZ', 49, NULL, '', 'user'),
	(73, 'Marcello Gasparini', 'marcello.gasparini44@yahoo.com', 'OHURZXUWQXQAVAHC', 38, NULL, '', 'user'),
	(74, 'Fabio Vegro', 'fabio.vegro56@infinitevoid.jap', 'LHFXQOREGWQFYXCC', 50, NULL, '', 'user'),
	(75, 'Ermenegilda Cucu', 'ermenegilda.cucu26@yahoo.com', 'CLKVMDFRYZGDYXXM', 48, NULL, '', 'user'),
	(76, 'Goku Anescu', 'goku.anescu30@malevolentshrine.com', 'ESFZWRHOMTDWLRLO', 35, NULL, '', 'user'),
	(77, 'Nicole Alfieri', 'nicole.alfieri80@hotmail.it', 'SHZFSJMCKFORDFXZ', 24, NULL, '', 'user'),
	(78, 'Carloamianto Borbone', 'carloamianto.borbone89@hotmail.it', 'QBTWLBMUSVZICFES', 40, NULL, '', 'user'),
	(79, 'Vittoria Borbone', 'vittoria.borbone13@outlook.com', 'QDRDPZQXCBEWBTZU', 36, NULL, '', 'user'),
	(80, 'Fabio Sprocati', 'fabio.sprocati11@infinitevoid.jap', 'EENJRVFVRBSDFVYE', 31, NULL, '', 'user'),
	(81, 'Carloamianto Cucu', 'carloamianto.cucu36@iisviolamarchesini.edu.it', 'IQZQLVKMAWDJCOKY', 36, NULL, '', 'user'),
	(82, 'Nicole Targa', 'nicole.targa61@google.com', 'MEKUPRDOKCFDJQZS', 28, NULL, '', 'user'),
	(83, 'Ermenegilda Rossi', 'ermenegilda.rossi64@google.com', 'YOGBACONSCWZFDQD', 16, NULL, '', 'user'),
	(84, 'Ermenegilda Morandi', 'ermenegilda.morandi99@infinitevoid.jap', 'LUXCYUULSNRDMNSI', 23, NULL, '', 'user'),
	(85, 'Irene Cherubin', 'irene.cherubin57@iisviolamarchesini.edu.it', 'GXALAPRILKXMSNKP', 49, NULL, '', 'user'),
	(86, 'Eleonora Sulek', 'eleonora.sulek28@infinitevoid.jap', 'WZDXUXDXJNKSSYHQ', 36, NULL, '', 'user'),
	(87, 'Goku Rossi', 'goku.rossi31@outlook.com', 'WZMXJFLKJHJLRKMC', 46, NULL, '', 'user'),
	(88, 'Fabio Rossi', 'fabio.rossi38@hotmail.it', 'KREZAJGNZVPMDEHW', 27, NULL, '', 'user'),
	(89, 'Enrico Sulek', 'enrico.sulek59@iisviolamarchesini.edu.it', 'FZERAOYEUHAMPPGK', 34, NULL, '', 'user'),
	(90, 'Sam Formaggio', 'sam.formaggio10@yahoo.com', 'UCITFLHMETXRGXPS', 19, NULL, '', 'user'),
	(91, 'Mario Morandi', 'mario.morandi41@outlook.com', 'XLSERUWAHUVWIBVU', 34, NULL, '', 'user'),
	(92, 'Sam Alfieri', 'sam.alfieri25@malevolentshrine.com', 'WAKBXTSOHTMCKEZA', 20, NULL, '', 'user'),
	(93, 'Francesca Formaggio', 'francesca.formaggio72@google.com', 'XPPQHCHCQNOYDSGX', 25, NULL, '', 'user'),
	(94, 'Vittoria Vegro', 'vittoria.vegro31@iisviolamarchesini.edu.it', 'TIMERFZQRJGTESXI', 19, NULL, '', 'user'),
	(95, 'Leopoldo Melon', 'leopoldo.melon77@hotmail.it', 'JJIDGWNTAUIEUHLT', 47, NULL, '', 'user'),
	(96, 'Elena Rossi', 'elena.rossi24@hotmail.it', 'WCJRFXFGRYVAIDNM', 18, NULL, '', 'user'),
	(97, 'Sam Alfieri', 'sam.alfieri13@google.com', 'QVEMHRUZCDCKXKPN', 50, NULL, '', 'user'),
	(98, 'Marcello Sterza', 'marcello.sterza22@malevolentshrine.com', 'DJVUACFSILZBUFDL', 39, NULL, '', 'user'),
	(99, 'John Formaggio', 'john.formaggio48@outlook.com', 'TQAFJKNHNYRGPVXP', 38, NULL, '', 'user'),
	(100, 'Goku Melon', 'goku.melon42@malevolentshrine.com', 'FQDOZEDAHKHPNUUI', 25, NULL, '', 'user'),
	(101, 'Sam Melon', 'sam.melon61@infinitevoid.jap', 'KPDBMFCPGLLAKWGJ', 49, NULL, '', 'user'),
	(102, 'Carloamianto Alfieri', 'carloamianto.alfieri40@yahoo.com', 'HNWWDGWNUPNQYTDJ', 46, NULL, '', 'user'),
	(103, 'Ermenegilda Morandi', 'ermenegilda.morandi66@iisviolamarchesini.edu.it', 'HCNMBUONSGYXSHMD', 44, NULL, '', 'user'),
	(104, 'John Zadra', 'john.zadra45@google.com', 'GDDLSYCNSSELYBMJ', 36, NULL, '', 'user'),
	(105, 'Enrico Cucu', 'enrico.cucu58@yahoo.com', 'EQHYEEVGMDZOGIJG', 32, NULL, '', 'user'),
	(107, 'Mario Melon', 'mario.melon79@outlook.com', 'PYQQOIOLAXZWFBKD', 30, NULL, '', 'user'),
	(108, 'Marcello Vegro', 'marcello.vegro54@infinitevoid.jap', 'TOIAXMZNBQIGGNRF', 26, NULL, '', 'user'),
	(110, 'Marcello Sterza', 'marcello.sterza43@hotmail.it', 'HIVSWMIESKWRGESM', 49, NULL, '', 'user'),
	(111, 'Leopoldo Alfieri', 'leopoldo.alfieri87@outlook.com', 'CHTDZCIRMAXMXCYW', 49, NULL, '', 'user'),
	(112, 'Nazza Gasparini', 'nazza.gasparini92@yahoo.com', 'DXQPYRBASWNFHDXL', 21, NULL, '', 'user'),
	(113, 'Ermenegilda Melon', 'ermenegilda.melon41@yahoo.com', 'RJRCBPVAGEHNHWTY', 36, NULL, '', 'user'),
	(114, 'Eleonora Gasparini', 'eleonora.gasparini56@infinitevoid.jap', 'WDSEUTRWEBPTNWUJ', 20, NULL, '', 'user'),
	(115, 'Elena Targa', 'elena.targa59@malevolentshrine.com', 'MJSCAYVGXQPXTVYT', 33, NULL, '', 'user'),
	(116, 'Eleonora Zadra', 'eleonora.zadra31@malevolentshrine.com', 'SRTUBCOKULVYRMSQ', 19, NULL, '', 'user'),
	(117, 'Mario Sulek', 'mario.sulek79@infinitevoid.jap', 'JFCLKBEHBJKHBHUN', 47, NULL, '', 'user'),
	(118, 'Nicole Cherubin', 'nicole.cherubin58@iisviolamarchesini.edu.it', 'NNTAPGEEGMKHLVGV', 33, NULL, '', 'user'),
	(119, 'Irene Vegro', 'irene.vegro83@hotmail.it', 'XMKHTXEKILQYGTQO', 44, NULL, '', 'user'),
	(120, 'Noelle Morandi', 'noelle.morandi68@malevolentshrine.com', 'GFBFLMJRJRTZYVUA', 26, NULL, '', 'user'),
	(121, 'Elena Targa', 'elena.targa76@hotmail.it', 'NTKLTKAJGTQDLELI', 34, NULL, '', 'user'),
	(122, 'Carloamianto Vegro', 'carloamianto.vegro33@yahoo.com', 'JVCHKNHXLOKVIATU', 50, NULL, '', 'user'),
	(123, 'Marcello Morandi', 'marcello.morandi58@google.com', 'TABSFBABMYNBAZYV', 39, NULL, '', 'user'),
	(124, 'John Vegro', 'john.vegro20@iisviolamarchesini.edu.it', 'EHUEMBSGKZJVKJUF', 38, NULL, '', 'user'),
	(125, 'Noelle Zadra', 'noelle.zadra16@iisviolamarchesini.edu.it', 'ASQULCNRWWESUEAF', 43, NULL, '', 'user'),
	(126, 'Enrico Cucu', 'enrico.cucu74@hotmail.it', 'SBAHMMUNURLTSBGN', 26, NULL, '', 'user'),
	(127, 'Marcello Borbone', 'marcello.borbone66@yahoo.com', 'ODYDCNHDCOLECHAQ', 18, NULL, '', 'user'),
	(128, 'Leopoldo Vegro', 'leopoldo.vegro80@iisviolamarchesini.edu.it', 'DANDSLFIOVOXIUJU', 34, NULL, '', 'user'),
	(129, 'Angelica Sterza', 'angelica.sterza79@yahoo.com', 'KGISOLKKZHWLBGNE', 40, NULL, '', 'user'),
	(130, 'Nicole Anescu', 'nicole.anescu68@infinitevoid.jap', 'NAFGLNKKVBVOCUCW', 41, NULL, '', 'user'),
	(131, 'Enrico Vegro', 'enrico.vegro43@infinitevoid.jap', 'THDGUOLXHICFYRPY', 17, NULL, '', 'user'),
	(132, 'Sam Vegro', 'sam.vegro85@iisviolamarchesini.edu.it', 'ZVYVJWPQETWDLSFM', 45, NULL, '', 'user'),
	(133, 'Angelica Borbone', 'angelica.borbone29@hotmail.it', 'HDYHSGMTFJKEEULR', 44, NULL, '', 'user'),
	(134, 'Fabio Zadra', 'fabio.zadra11@yahoo.com', 'VZWKGUOGZOMLACMR', 30, NULL, '', 'user'),
	(135, 'Eleonora Rossi', 'eleonora.rossi76@infinitevoid.jap', 'XFTOFDXEBPWVGENN', 25, NULL, '', 'user'),
	(136, 'Vittoria Vegro', 'vittoria.vegro26@yahoo.com', 'KTVQVAWWGWNWPOQM', 36, NULL, '', 'user'),
	(137, 'Irene Gasparini', 'irene.gasparini31@yahoo.com', 'RYBQJAIYKVXQQVAD', 37, NULL, '', 'user'),
	(138, 'Sam Melon', 'sam.melon97@infinitevoid.jap', 'AQHQDWUGFXVDBJCN', 17, NULL, '', 'user'),
	(139, 'Sam Alfieri', 'sam.alfieri85@hotmail.it', 'LMLANSXBSABSKRLI', 16, NULL, '', 'user'),
	(140, 'Nazza Gasparini', 'nazza.gasparini29@yahoo.com', 'GHZQAMRBKNHEYVJH', 40, NULL, '', 'user'),
	(141, 'Angelica Rossi', 'angelica.rossi51@infinitevoid.jap', 'PAYMUTNHGJQNYMPW', 43, NULL, '', 'user'),
	(142, 'Goku Vegro', 'goku.vegro42@malevolentshrine.com', 'OTXWZFOZHHOLLNFK', 38, NULL, '', 'user'),
	(143, 'Irene Alfieri', 'irene.alfieri50@malevolentshrine.com', 'EVCXLDGMGFYITZKI', 41, NULL, '', 'user'),
	(144, 'Nicole Targa', 'nicole.targa67@hotmail.it', 'TLZAWTKDNKSCWXDH', 34, NULL, '', 'user'),
	(145, 'Vittoria Borbone', 'vittoria.borbone58@hotmail.it', 'CJUXNUPGXSZQJRVH', 44, NULL, '', 'user'),
	(146, 'Elena Morandi', 'elena.morandi18@yahoo.com', 'ABAUPEZLDBDXPYNU', 27, NULL, '', 'user'),
	(147, 'Noelle Borbone', 'noelle.borbone58@yahoo.com', 'DMLKXKJOWIKRYGZE', 46, NULL, '', 'user'),
	(148, 'Goku Rossi', 'goku.rossi21@yahoo.com', 'PKDWPPIRABBGUQDD', 24, NULL, '', 'user'),
	(149, 'Eleonora Sulek', 'eleonora.sulek28@iisviolamarchesini.edu.it', 'SOGWZEDGUYYFZIWU', 44, NULL, '', 'user'),
	(150, 'Francesca Sterza', 'francesca.sterza15@iisviolamarchesini.edu.it', 'YTCZHIYOUKTPYKKI', 43, NULL, '', 'user'),
	(151, 'Marcello Alfieri', 'marcello.alfieri70@google.com', 'VRTPARMPZPBURGDF', 41, NULL, '', 'user'),
	(152, 'Elena Morandi', 'elena.morandi89@iisviolamarchesini.edu.it', 'MEYDPMIKWMFXRIWH', 22, NULL, '', 'user'),
	(153, 'Francesca Vegro', 'francesca.vegro41@yahoo.com', 'KYMQUSTWYIJAHEGC', 26, NULL, '', 'user'),
	(154, 'Leopoldo Formaggio', 'leopoldo.formaggio98@outlook.com', 'IGZUCDSGQTLZJRNL', 44, NULL, '', 'user'),
	(155, 'Goku Sulek', 'goku.sulek83@yahoo.com', 'OQBSEKOBMIAUXQUL', 36, NULL, '', 'user'),
	(156, 'Mario Cucu', 'mario.cucu93@malevolentshrine.com', 'PDYKBJSZQVGBLHCK', 27, NULL, '', 'user'),
	(157, 'Carloamianto Morandi', 'carloamianto.morandi21@outlook.com', 'GSNSTDKGDWHSBNZP', 24, NULL, '', 'user'),
	(162, 'Mario Formaggio', 'mario.formaggio42@iisviolamarchesini.edu.it', 'DTVIJWENYOFQSLCD', 36, NULL, '', 'user'),
	(163, 'Nazza Vegro', 'nazza.vegro23@iisviolamarchesini.edu.it', 'CJZMOQRKUYRYOJKA', 25, NULL, '', 'user'),
	(164, 'Goku Alfieri', 'goku.alfieri84@hotmail.it', 'POKUTLNRICMFSELG', 27, NULL, '', 'user'),
	(165, 'Mario Rossi', 'mario.rossi85@google.com', 'JTMVOWHPYMHNRNOP', 35, NULL, '', 'user'),
	(166, 'Elena Cucu', 'elena.cucu14@malevolentshrine.com', 'NONSIMYMXXQMPASW', 49, NULL, '', 'user'),
	(167, 'Angelica Targa', 'angelica.targa13@hotmail.it', 'FWSSXVNSGTGMCMQZ', 42, NULL, '', 'user'),
	(168, 'Nicole Melon', 'nicole.melon34@malevolentshrine.com', 'HZISXCUSRBCFAJFL', 43, NULL, '', 'user'),
	(169, 'Irene Zadra', 'irene.zadra59@hotmail.it', 'JBRGKIXTIZTIKUNH', 16, NULL, '', 'user'),
	(170, 'Eleonora Sprocati', 'eleonora.sprocati28@malevolentshrine.com', 'ZUSQZBZSCELCWYCH', 27, NULL, '', 'user'),
	(171, 'Vittoria Alfieri', 'vittoria.alfieri91@yahoo.com', 'AHSTWWIFIKKFPZGS', 27, NULL, '', 'user'),
	(172, 'Nazza Vegro', 'nazza.vegro70@infinitevoid.jap', 'EGIULMERKWKSMRVM', 40, NULL, '', 'user'),
	(173, 'Vittoria Vegro', 'vittoria.vegro49@hotmail.it', 'BIOCFAYCCKNDAPEF', 21, NULL, '', 'user'),
	(174, 'Marcello Sulek', 'marcello.sulek83@iisviolamarchesini.edu.it', 'XBRQXXERZAESMTWW', 28, NULL, '', 'user'),
	(175, 'Ermenegilda Sprocati', 'ermenegilda.sprocati12@infinitevoid.jap', 'TEEPGOSLDSVENYFW', 27, NULL, '', 'user'),
	(176, 'Ermenegilda Cucu', 'ermenegilda.cucu90@google.com', 'YFQDXKLLJKTBIVKE', 22, NULL, '', 'user'),
	(177, 'Mario Rossi', 'mario.rossi39@iisviolamarchesini.edu.it', 'VUAGDVGSCQXNROVK', 28, NULL, '', 'user'),
	(178, 'Noelle Sulek', 'noelle.sulek93@outlook.com', 'TECVZZMYSWRYHURG', 48, NULL, '', 'user'),
	(179, 'John Cucu', 'john.cucu41@yahoo.com', 'SIAERRYWCXWERQHU', 16, NULL, '', 'user'),
	(180, 'Leopoldo Sprocati', 'leopoldo.sprocati70@google.com', 'WLGUZFHBMYJVTJYA', 34, NULL, '', 'user'),
	(181, 'Mario Formaggio', 'mario.formaggio93@hotmail.it', 'PNSSITBAMCTZKOZH', 17, NULL, '', 'user'),
	(182, 'Irene Sprocati', 'irene.sprocati87@malevolentshrine.com', 'VCXFPHIJNFPFCNZL', 49, NULL, '', 'user'),
	(183, 'Ermenegilda Sterza', 'ermenegilda.sterza81@google.com', 'SRYEUDPPEPHRVZGJ', 23, NULL, '', 'user'),
	(184, 'Leopoldo Anescu', 'leopoldo.anescu62@google.com', 'HIMFHLEMNFKFKXID', 42, NULL, '', 'user'),
	(185, 'Vittoria Sulek', 'vittoria.sulek82@hotmail.it', 'SMWYCKCMQFXNWOED', 35, NULL, '', 'user'),
	(186, 'Eleonora Cherubin', 'eleonora.cherubin48@infinitevoid.jap', 'MMYERJDGXCSEZQHQ', 41, NULL, '', 'user'),
	(187, 'Carloamianto Gasparini', 'carloamianto.gasparini83@yahoo.com', 'RXXTOBGAZJDRBMIV', 42, NULL, '', 'user'),
	(188, 'Sam Cherubin', 'sam.cherubin80@yahoo.com', 'RVAYYLRLCDQTUUHG', 24, NULL, '', 'user'),
	(189, 'Noelle Formaggio', 'noelle.formaggio27@infinitevoid.jap', 'CAPYENIPUSVNCOYF', 43, NULL, '', 'user'),
	(190, 'Francesca Melon', 'francesca.melon17@google.com', 'RNNYPBKCTVGPRLSP', 45, NULL, '', 'user'),
	(191, 'Eleonora Targa', 'eleonora.targa65@outlook.com', 'KZALHYCPLZSWENQA', 29, NULL, '', 'user'),
	(192, 'Nicole Cucu', 'nicole.cucu29@yahoo.com', 'HLPJCUZMRIDNETJT', 50, NULL, '', 'user'),
	(193, 'Angelica Gasparini', 'angelica.gasparini63@google.com', 'BWNBSQKZIPSGVPIC', 30, NULL, '', 'user'),
	(194, 'Francesca Cherubin', 'francesca.cherubin74@hotmail.it', 'IMCENMHRNHNRLZNB', 47, NULL, '', 'user'),
	(196, 'Angelica Targa', 'angelica.targa49@hotmail.it', 'NKUYQKCIYKSUCOHV', 31, NULL, '', 'user'),
	(197, 'Fabio Targa', 'fabio.targa24@infinitevoid.jap', 'GFAFBXINLIYVOLHA', 35, NULL, '', 'user'),
	(198, 'Fabio Morandi', 'fabio.morandi75@hotmail.it', 'PDSDDKMVFPZAJLLM', 21, NULL, '', 'user'),
	(200, 'Leopoldo Melon', 'leopoldo.melon76@malevolentshrine.com', 'NEKXQHKCYXMMDNYI', 30, NULL, '', 'user'),
	(201, 'Matteo Salviettini', 'matteo.salviettini@salvietta.com', 'MSSSOO00OO', 100, NULL, '', 'user'),
	(202, 'Martino Crodino', 'martino.crodino@crodino.com', 'MCROSKLKLS', 22, NULL, '', 'user'),
	(205, 'Francesco Marzano', 'francesco.marzaa104@gmail.com', 'FMEMFOMFO56MF', 27, '205_17195669714848.jpg', '', 'user'),
	(216, 'marcello targone', 'tort.mar@rr.com', 'MRTHFISHFI', 68, '216_17195844455571.jpg', '$2y$10$lU13/v1xAMsws05i8dJwdurjuCH048ONlG2x4GcOuR1irRulI3Zsi', 'editor');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
